# Generated by Django 6.1.1 on 2026-09-26 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(editable=False, max_length=35, unique=True)),
                ('bill_type', models.CharField(choices=[('OPD', 'OPD Doctor Consultation'), ('IPD', 'IPD Inpatient Hospitalization'), ('DIAGNOSTIC', 'Diagnostic / Pathology Test'), ('PHARMACY', 'Pharmacy Purchase'), ('COMBINED', 'Combined / Package Bill')], default='GENERAL', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial Paid'), ('Unpaid', 'Unpaid (Due)')], default='Unpaid', max_length=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Doctor Fee', 'Doctor Consultation Fee'), ('Lab Test', 'Diagnostic / Lab Test'), ('Bed Charge', 'Bed / Cabin Charge'), ('Medicine', 'Medicine / Pharmacy'), ('Procedure / OT', 'Surgery / Procedure / OT Charge'), ('Nursing', 'Nursing & Service Charge'), ('Other', 'Other Service')], default='Other', max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=35, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash Counter'), ('bKash', 'bKash (Mobile Banking)'), ('Nagad', 'Nagad (Mobile Banking)'), ('Rocket', 'Rocket (DBBL)'), ('Card', 'Credit / Debit Card (POS)'), ('Bank', 'Bank Transfer / Cheque')], default='Cash', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text='e.g. bKash TrxID / Card Slip No', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
