# Generated by Django 6.1.1 on 2026-09-26 21:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Staff Salary, Electricity & Utility, Medical Supplies, Doctor Commission Payout, Equipment Maintenance, Rent, Marketing', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
            },
        ),
        migrations.CreateModel(
            name='HospitalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='WebKoders Healthcare & Hospital BD', max_length=200)),
                ('hospital_tagline', models.CharField(default='Modern Healthcare & Diagnostic Center', max_length=255)),
                ('reg_license_no', models.CharField(blank=True, default='DGHS-REG-10492/2026', max_length=100, null=True)),
                ('phone', models.CharField(default='01826027203', max_length=50)),
                ('hotline', models.CharField(blank=True, default='+880 1711-122233', max_length=50, null=True)),
                ('email', models.EmailField(default='hospitalsoftwarebd@gmail.com', max_length=254)),
                ('website', models.CharField(default='www.hospitalsoftwarebd.com', max_length=150)),
                ('address', models.TextField(default='437 Shahid Jahanara Imam Road, New Elephant Road, Dhaka-1205')),
                ('currency_symbol', models.CharField(default='৳', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('pdf_header_banner', models.ImageField(blank=True, help_text='Banner letterhead for prescription pad & lab reports', null=True, upload_to='settings/')),
                ('authorized_signature_seal', models.ImageField(blank=True, help_text='Official Director/Doctor seal & signature image', null=True, upload_to='settings/')),
                ('invoice_footer_note', models.TextField(blank=True, default='* Payment is non-refundable. Please keep this money receipt for future reference.')),
                ('lab_report_footer_note', models.TextField(blank=True, default='* This is an authorized digital diagnostic laboratory report.')),
                ('prescription_footer_note', models.TextField(blank=True, default='* Take medicines as advised. For emergency, visit our casualty department.')),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_provider', models.CharField(choices=[('BulkSMSBD', 'BulkSMSBD (Bangladesh)'), ('Greenweb', 'Greenweb SMS Gateway'), ('SSLWireless', 'SSL Wireless SMS Gateway'), ('Custom', 'Custom HTTP SMS API URL')], default='BulkSMSBD', max_length=30)),
                ('sms_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('sms_sender_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sms_custom_url', models.CharField(blank=True, max_length=255, null=True)),
                ('sms_on_registration', models.BooleanField(default=True)),
                ('sms_on_appointment', models.BooleanField(default=True)),
                ('sms_on_lab_ready', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_no', models.CharField(editable=False, max_length=35, unique=True)),
                ('title', models.CharField(help_text='e.g. September Staff Salary, Generator Diesel, Lab Reagent purchase', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash (ক্যাশ)'), ('Bank', 'Bank Transfer / Cheque'), ('bKash', 'bKash'), ('Nagad', 'Nagad'), ('Card', 'Credit/Debit Card')], default='Cash', max_length=20)),
                ('paid_to', models.CharField(blank=True, help_text='Name of vendor / employee / payee', max_length=150, null=True)),
                ('voucher_receipt', models.FileField(blank=True, null=True, upload_to='vouchers/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='billing.expensecategory')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
