# Generated by Django 6.1.1 on 2026-09-26 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Paracetamol, Esomeprazole, Azithromycin, Cefixime', max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Tablet, Capsule, Syrup, Injection, Ointment, Suspension, Drops', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Medicine Categories',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(help_text='e.g. Napa Extra, Maxpro, Seclo, Zithrox', max_length=150)),
                ('strength', models.CharField(blank=True, help_text='e.g. 500mg, 20mg, 1gm, 5ml/100ml', max_length=50, null=True)),
                ('company_name', models.CharField(help_text='e.g. Square Pharmaceuticals, Beximco, Incepta, Renata', max_length=150)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='MRP per piece/strip/bottle', max_digits=10)),
                ('reorder_level', models.PositiveIntegerField(default=50, help_text='Alert when total stock falls below this quantity')),
                ('is_active', models.BooleanField(default=True)),
                ('generic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='pharmacy.genericname')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='pharmacy.medicinecategory')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('purchase_cost_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('selling_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy.medicine')),
            ],
            options={
                'verbose_name_plural': 'Medicine Batches',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='PharmacySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(editable=False, max_length=35, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_purchases', to='patients.patient')),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacySaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicinebatch')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.pharmacysale')),
            ],
        ),
    ]
