# Generated by Django 6.1.1 on 2026-09-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='brand_name',
            field=models.CharField(db_index=True, help_text='e.g. Napa Extra, Maxpro, Seclo, Zithrox', max_length=150),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='company_name',
            field=models.CharField(db_index=True, help_text='e.g. Square Pharmaceuticals, Beximco, Incepta, Renata', max_length=150),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
