# Generated by Django 6.1.1 on 2026-09-26 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(help_text='e.g. CBC, RBS, LFT, S.CREATININE, USG-WHOLE-ABDOMEN', max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('specimen', models.CharField(default='Blood', help_text='e.g. Blood, Urine, Stool, Swab, Sputum, None', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Patient Charge (BDT)', max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Lab Chemical/Internal Cost', max_digits=10)),
                ('delivery_time_hours', models.PositiveIntegerField(default=24, help_text='Report delivery time in hours')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Hematology, Biochemistry, Radiology, Microbiology, Serology', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Test Categories',
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(editable=False, max_length=35, unique=True)),
                ('external_doctor_name', models.CharField(blank=True, help_text='If referred by an outside doctor', max_length=150, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('doctor_commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sample Collected', 'Sample Collected'), ('In Progress', 'In Progress'), ('Completed', 'Completed (Report Ready)'), ('Delivered', 'Delivered to Patient'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30)),
                ('sample_collected_at', models.DateTimeField(blank=True, null=True)),
                ('report_ready_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patient')),
                ('referred_by_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_lab_orders', to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sample_collected', models.BooleanField(default=False)),
                ('report_completed', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diagnostics.laborder')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostics.labtest')),
            ],
        ),
        migrations.AddField(
            model_name='labtest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='diagnostics.testcategory'),
        ),
        migrations.CreateModel(
            name='TestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Hemoglobin, Fasting Blood Sugar, SGPT (ALT), Serum Creatinine', max_length=150)),
                ('unit', models.CharField(blank=True, help_text='e.g. g/dL, mg/dL, U/L, %', max_length=50, null=True)),
                ('reference_range', models.CharField(blank=True, help_text='e.g. Male: 13.5-17.5, Female: 12.0-15.5', max_length=200, null=True)),
                ('order_index', models.PositiveIntegerField(default=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='diagnostics.labtest')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(blank=True, max_length=255, null=True)),
                ('flag', models.CharField(blank=True, help_text='Normal / High / Low / Positive / Negative', max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='diagnostics.laborderitem')),
                ('tested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tested_results', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_results', to=settings.AUTH_USER_MODEL)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostics.testparameter')),
            ],
        ),
    ]
