# Generated by Django 6.1.1 on 2026-09-26 20:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(help_text='e.g. Bed-101, Cabin-204, ICU-05', max_length=50, unique=True)),
                ('floor', models.CharField(default='1st Floor', max_length=50)),
                ('daily_charge', models.DecimalField(decimal_places=2, help_text='Charge per 24 hours (BDT)', max_digits=10)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Cleaning', 'Cleaning / Sanitizing'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
                ('description', models.CharField(blank=True, help_text='e.g. Attached Bath, AC, TV', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. General Ward (Male), General Ward (Female), AC Cabin, Non-AC Cabin, VIP Suite, ICU, CCU, NICU', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(editable=False, max_length=35, unique=True)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('initial_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reason_for_admission', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Admitted', 'Currently Admitted'), ('Discharged', 'Discharged'), ('Transferred', 'Transferred')], default='Admitted', max_length=20)),
                ('discharge_summary', models.TextField(blank=True, null=True)),
                ('discharge_advice', models.TextField(blank=True, null=True)),
                ('admitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('admitted_under_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_patients', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='wards.bed')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='ward_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='wards.wardtype'),
        ),
    ]
