# Generated by Django 6.1.1 on 2026-09-26 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(help_text='e.g. Professor & Head of Dept / Senior Consultant', max_length=150)),
                ('degrees', models.CharField(help_text='e.g. MBBS, FCPS (Medicine), MD', max_length=255)),
                ('bmdc_reg_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='BMDC Reg No')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('follow_up_fee', models.DecimalField(decimal_places=2, default=300.0, max_digits=10)),
                ('commission_rate_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Diagnostic referral commission %', max_digits=5)),
                ('room_number', models.CharField(default='Room-101', max_length=50)),
                ('available_days', models.CharField(default='Sat, Sun, Mon, Tue, Wed, Thu', max_length=150)),
                ('visiting_hours', models.CharField(default='5:00 PM - 9:00 PM', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='doctors.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('chief_complaints', models.TextField(blank=True, help_text='Chief complaints / Symptoms', null=True)),
                ('history_and_findings', models.TextField(blank=True, help_text='On Examination (O/E), BP, Pulse, Weight, etc.', null=True)),
                ('diagnosis', models.TextField(blank=True, help_text='Provisional / Final Diagnosis', null=True)),
                ('tests_advised', models.TextField(blank=True, help_text='Investigation / Lab Tests Advised', null=True)),
                ('advice', models.TextField(blank=True, help_text='General Advice / Diet / Lifestyle', null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(help_text='e.g. Tab. Napa Extra 500mg', max_length=200)),
                ('dosage', models.CharField(help_text='e.g. 1+0+1, 1+1+1, 0+0+1', max_length=100)),
                ('duration', models.CharField(help_text='e.g. 5 days, 1 month, Continue', max_length=100)),
                ('instruction', models.CharField(blank=True, help_text='e.g. After meal / Before meal', max_length=150, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='doctors.prescription')),
            ],
        ),
    ]
